// This file is automatically generated.

#include <avr/io.h>
#include <util/delay_basic.h>
#include <stdbool.h>

struct list {
    uint8_t size;
    void* values;
};

struct tuple2 {
    void* value0;
    void* value1;
};

struct tuple6 {
    void* value0;
    void* value1;
    void* value2;
    void* value3;
    void* value4;
    void* value5;
};

static void input_pin9();

static void stream_1(uint8_t arg, void* value);

static void input_pin9() {
  bool temp0;
  temp0 = (PINB & (1 << PB1)) == 0U;
  stream_1(0, (void*)(&temp0));
}

static void stream_1(uint8_t arg, void* value) {
  bool input_0 = *((bool*)value);
  if (input_0) {
    PORTD |= (1 << PD6);
  } else {
    PORTD &= ~(1 << PD6);
  }
}

int main(void) {
  DDRB &= ~(1 << PB1);
  PORTB |= (1 << PB1);
  DDRD |= (1 << PD6);
  while (1) {
    input_pin9();
  }
  return 0;
}
